# Generated by Django 4.1.3 on 2022-11-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('A', 'Admin'), ('M', 'Moderator'), ('S', 'Simple')], default='S', max_length=20),
        ),
    ]
