# Generated by Django 4.1.3 on 2022-11-01 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'OrganizationProject',
                'verbose_name_plural': 'OrganizationProjects',
                'db_table': 'OrganizationProjects',
            },
        ),
        migrations.CreateModel(
            name='OrganizationObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organizationproject')),
            ],
            options={
                'verbose_name': 'OrganizationObject',
                'verbose_name_plural': 'OrganizationObjects',
                'db_table': 'OrganizationObjects',
            },
        ),
    ]
