# Generated by Django 4.1.3 on 2022-11-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationobject',
            name='name',
            field=models.CharField(default='TestName', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationproject',
            name='name',
            field=models.CharField(default='TestName', max_length=30),
            preserve_default=False,
        ),
    ]
